version: 0.2

phases:
  pre_build:
    commands:
      # Login to ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772053707.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=724772053707.dkr.ecr.us-east-1.amazonaws.com/my-app-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      # Build Docker image
      - echo Building the Docker image...
      - cd docker-webapp  # Navigate to the docker-webapp directory
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      # Push Docker image to ECR
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip/**/*'  # Cache Python dependencies
