version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Login to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 724772053707.dkr.ecr.us-east-1.amazonaws.com/my-app-repo
  build:
    commands:
      # Build the Docker image
      - docker build -t $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      # Tag the Docker image
      - docker tag $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION $ECR_REPO:latest
  post_build:
    commands:
      # Push the Docker image to ECR
      - docker push $ECR_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $ECR_REPO:latest
