---
- name: Deploy Flask App with Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image (Optional if using remote registry)
      command: docker pull flask-app

    - name: Remove existing container (if running)
      command: docker rm -f flask-app
      ignore_errors: yes

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 --name flask-app flask-app

